language: node_js
node_js:
    - 0.10

before_script:
    - npm install -g mocha
    - npm install -g istanbul

script:
    - mocha ./test/handler.js
    - istanbul cover _mocha --report lcovonly -- -R spec --recursive && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
