exports.list = function(req, res) {
    setTimeout(function() {
        res.json(200, {
            code: 200,
            msg: {
                parentId: 'dsafdfs',
                id: '00E90000000F8lqEAC',
                name: '绍兴团购组',
                salesAmount: 12103238,
                yesterdaySalesAmount: 523232212,
                salesIncome: 34329423,
                salesAdIncome: 2341234,
                onlineDealGroup: 291,
                onlineKABAccount: 3993,
                newDealGroup: 2323,
                newShop: 12345,
                onlineShop: 54321,
                almostExpired: 1000,
                isLast: true,
                updateTime: '2013-11-11 11:11:11',
                keyShopCnt:901,
                grossMargin:0.345,
                dealPerShop:1.67,
                offlineDealgrp:901,
                walkInPercent:0.345,
                cashDealgrpPercent:0.345,
                visitCnt:901,
                lastBrother: {
                    id: '00E90000000F8vCEAS',
                    name: '绍兴团购无业绩归属组'
                },

                nextBrother: {
                    id: '00E90000000F8vCEAS',
                    name: '绍兴团购无业绩归属组'
                },

                child: [{
                    parentId: '00E90000000F8lqEAC',
                    id: '938sdsdf',
                    name: '布莱尔',
                    salesAmount: 1210338,
                    yesterdaySalesAmount: 22212,
                    salesIncome: 3433,
                    salesAdIncome: 2234,
                    salesAdAmount: 323,
                    onlineDealGroup: 291,
                    onlineKABAccount: 393,
                    newShop: 143,
                    onlineShop: 521,
                    almostExpired: 11,
                    newDealGroup: 3,
                    keyShopCnt:901,
                    grossMargin:0.345,
                    dealPerShop:1.67,
                    offlineDealgrp:901,
                    walkInPercent:0.345,
                    cashDealgrpPercent:0.345,
                    visitCnt:901
                }, {
                    parentId: '00E90000000F8lqEAC',
                    id: '039883dd',
                    name: '昆丁',
                    teamAmount: 0,
                    salesAmount: 323874382,
                    yesterdaySalesAmount: 0,
                    yesterdayTeamAmount: 0,
                    salesIncome: 0,
                    salesAdIncome: 100,
                    onlineDealGroup: 0,
                    onlineKABAccount: 0,
                    newShop: 12345,
                    onlineShop: 54321,
                    almostExpired: 3,
                    newDealGroup: 0,
                    keyShopCnt:901,
                    grossMargin:0.345,
                    dealPerShop:1.67,
                    offlineDealgrp:901,
                    walkInPercent:0.345,
                    cashDealgrpPercent:0.345,
                    visitCnt:901
                }, {
                    parentId: '00E90000000F8lqEAC',
                    id: '03988322dd',
                    name: '麦克',
                    teamAmount: 0,
                    salesAmount: 323874382,
                    yesterdaySalesAmount: 0,
                    yesterdayTeamAmount: 0,
                    salesIncome: 0,
                    salesAdIncome: 100,
                    onlineDealGroup: 0,
                    onlineKABAccount: 0,
                    newShop: 12345,
                    onlineShop: 54321,
                    almostExpired: 4,
                    newDealGroup: 0,
                    keyShopCnt:901,
                    grossMargin:0.345,
                    dealPerShop:1.67,
                    offlineDealgrp:901,
                    walkInPercent:0.345,
                    cashDealgrpPercent:0.345,
                    visitCnt:901,
                }, {
                    parentId: '00E90000000F8lqEAC',
                    id: '039322dd',
                    name: '杰克',
                    teamAmount: 0,
                    salesAmount: 323874382,
                    yesterdaySalesAmount: 0,
                    yesterdayTeamAmount: 0,
                    salesIncome: 0,
                    salesAdIncome: 100,
                    onlineDealGroup: 0,
                    newShop: 12345,
                    onlineShop: 54321,
                    onlineKABAccount: 0,
                    almostExpired: 2,
                    newDealGroup: 0,
                    keyShopCnt:901,
                    grossMargin:0.345,
                    dealPerShop:1.67,
                    offlineDealgrp:901,
                    walkInPercent:0.345,
                    cashDealgrpPercent:0.345,
                    visitCnt:901
                }]
            }
        })
    }, 1000)
}